export const GET_GRAPH_LIST_REQUEST = 'GET_GRAPH_LIST_REQUEST';
export const GET_GRAPH_LIST_SUCCESS = 'GET_GRAPH_LIST_SUCCESS';
export const GET_GRAPH_LIST_ERROR   = 'GET_GRAPH_LIST_ERROR';

export const SELECT_GRAPH_REQUEST = 'SELECT_GRAPH_REQUEST';
export const SELECT_GRAPH_SUCCESS = 'SELECT_GRAPH_SUCCESS';
export const SELECT_GRAPH_ERROR   = 'SELECT_GRAPH_ERROR';

export const ADD_GRAPH_REQUEST = 'ADD_GRAPH_REQUEST';
export const ADD_GRAPH_SUCCESS = 'ADD_GRAPH_SUCCESS';
export const ADD_GRAPH_ERROR   = 'ADD_GRAPH_ERROR';

export const SHOW_ADD_GRAPH_MODAL = 'SHOW_ADD_GRAPH_MODAL';
export const HIDE_ADD_GRAPH_MODAL = 'HIDE_ADD_GRAPH_MODAL';

export const GET_POINTS_REQUEST = 'GET_POINTS_REQUEST';
export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS';
export const GET_POINTS_ERROR   = 'GET_POINTS_ERROR';

export const ADD_POINT_REQUEST = 'ADD_POINT_REQUEST';
export const ADD_POINT_SUCCESS = 'ADD_POINT_SUCCESS';
export const ADD_POINT_ERROR   = 'ADD_POINT_ERROR';